Eticaret.Presentation/Models/CheckoutViewModel.cs
using System.ComponentModel.DataAnnotations;

namespace Eticaret.Presentation.Models
{
    public class CheckoutViewModel
    {
        [Required(ErrorMessage ="Şehir Seçiniz.")]
        public string City { get; set; }

        [Required(ErrorMessage = "Ad Giriniz.")]
        public string FirstName { get; set; }

        [Required(ErrorMessage = "Soyad Giriniz.")]
        public string LastName { get; set; }

        [Required(ErrorMessage = "Telefon Giriniz.")]
        public string Phone { get; set; }
        
        [Required(ErrorMessage = "Adres Giriniz.")]
        public string Address { get; set; }
    }
}

Eticaret.Presentation/Controllers/CheckoutController.cs
using Eticaret.Business.Helpers;
using Eticaret.Business.Services;
using Eticaret.Entities;
using Eticaret.Presentation.Helpers;
using Eticaret.Presentation.Models;
using Microsoft.AspNetCore.Mvc;
using System;

namespace Eticaret.Presentation.Controllers
{
    public class CheckoutController : Controller
    {
        IOrderService _orderService;
        ICookieHelper _cookieHelper;

        public CheckoutController(IOrderService orderService, ICookieHelper cookieHelper)
        {
            _orderService = orderService;
            _cookieHelper = cookieHelper;
        }

        public IActionResult Index()
        {
            return View();
        }
        [HttpPost]
        public IActionResult Index(CheckoutViewModel model)
        {
            if (model == null)
            {
                return RedirectToAction("Home", "Index");

            }
            if (ModelState.IsValid)
            {
                Order ord = new Order();
                ord.Address = model.Address;
                ord.City = Convert.ToInt32(model.City);
                ord.Date = DateTime.Now;
                ord.FirstName = model.FirstName;    
                ord.LastName = model.LastName;
                ord.Phone = model.Phone;
                var token = _cookieHelper.Get(CookieTypes.basket, Request);
                var basket = BasketHelper.GetMethods.Get(token);
                var orderJson = Newtonsoft.Json.JsonConvert.SerializeObject(basket);

                ord.OrderDetail = orderJson;// json db ye gönderildi.
                //Json
                _orderService.Add(ord);
                return RedirectToAction("Checkout", "OrderOk");
            }
            return View();
        }
    }
}

Eticaret.Presentation/ViewComponents/OrderDetailViewComponent.cs
using Eticaret.Business.Helpers;
using Eticaret.Presentation.Helpers;
using Microsoft.AspNetCore.Mvc;

namespace Eticaret.Presentation.ViewComponents
{
    public class OrderDetailViewComponent : ViewComponent
    {
        ICookieHelper _cookieHelper;
        public OrderDetailViewComponent(ICookieHelper cookieHelper)
        {
            _cookieHelper = cookieHelper;
        }
        public IViewComponentResult Invoke()
        {
            var tokenKey = _cookieHelper.Get(CookieTypes.basket, Request);
            var basket = BasketHelper.GetMethods.Get(tokenKey);

            return View(basket);
        }
    }
}

Eticaret.Presentation/Views/Checkout/Index.cshtml
@model CheckoutViewModel
@{
    Layout = "_BasketLayout";
}





<div class="single-product-area">
    <div class="zigzag-bottom"></div>
    <div class="container">
        <div class="row">
            <div class="col-md-6 col-md-offset-3">
                <div class="product-content-right">
                    <div class="woocommerce">
                        <div class="woocommerce-info">
                            Returning customer? <a class="showlogin" data-toggle="collapse" href="#login-form-wrap" aria-expanded="false" aria-controls="login-form-wrap">Click here to login</a>
                        </div>

                        <form id="login-form-wrap" class="login collapse" method="post">


                            <p>If you have shopped with us before, please enter your details in the boxes below. If you are a new customer please proceed to the Billing &amp; Shipping section.</p>

                            <p class="form-row form-row-first">
                                <label for="username">
                                    Username or email <span class="required">*</span>
                                </label>
                                <input type="text" id="username" name="username" class="input-text">
                            </p>
                            <p class="form-row form-row-last">
                                <label for="password">
                                    Password <span class="required">*</span>
                                </label>
                                <input type="password" id="password" name="password" class="input-text">
                            </p>
                            <div class="clear"></div>


                            <p class="form-row">
                                <input type="submit" value="Login" name="login" class="button">
                                <label class="inline" for="rememberme"><input type="checkbox" value="forever" id="rememberme" name="rememberme"> Remember me </label>
                            </p>
                            <p class="lost_password">
                                <a href="#">Lost your password?</a>
                            </p>

                            <div class="clear"></div>
                        </form>

                        <div class="woocommerce-info">
                            Have a coupon? <a class="showcoupon" data-toggle="collapse" href="#coupon-collapse-wrap" aria-expanded="false" aria-controls="coupon-collapse-wrap">Click here to enter your code</a>
                        </div>

                        <form id="coupon-collapse-wrap" method="post" class="checkout_coupon collapse">

                            <p class="form-row form-row-first">
                                <input type="text" value="" id="coupon_code" placeholder="Coupon code" class="input-text" name="coupon_code">
                            </p>

                            <p class="form-row form-row-last">
                                <input type="submit" value="Apply Coupon" name="apply_coupon" class="button">
                            </p>

                            <div class="clear"></div>
                        </form>

                        <form enctype="multipart/form-data" class="checkout" method="post" asp-controller="Checkout" asp-action="Index" name="checkout">

                            <div id="customer_details" class="col2-set">
                                <div class="col-1">
                                    <div class="woocommerce-billing-fields">
                                        <h3>Billing Details</h3>
                                        <p id="billing_country_field" class="form-row form-row-wide address-field update_totals_on_change validate-required woocommerce-validated">
                                            <label class="" for="billing_country">
                                                City <abbr title="required" class="required">*</abbr>
                                            </label>
                                            <select class="country_to_state country_select" asp-for="City">
                                                <option value="">Select a City…</option>
                                                <option value="34">İstanbul</option>
                                                <option value="01">Adana</option>
                                                <option value="06">Ankara</option>
                                            </select>
                                            <span asp-validation-for="City"></span>
                                        </p>

                                        <p id="billing_first_name_field" class="form-row form-row-first validate-required">
                                            <label class="" for="billing_first_name">
                                                First Name <abbr title="required" class="required">*</abbr>
                                            </label>
                                            <input type="text" value="" placeholder="" asp-for="FirstName" class="input-text ">
                                            <span asp-validation-for="FirstName"></span>
                                        </p>

                                        <p id="billing_last_name_field" class="form-row form-row-last validate-required">
                                            <label class="" for="billing_last_name">
                                                Last Name <abbr title="required" class="required">*</abbr>
                                            </label>
                                            <input type="text" value="" placeholder="" asp-for="LastName" class="input-text ">
                                            <span asp-validation-for="LastName"></span>
                                        </p>
                                        <div class="clear"></div>


                                        <p id="billing_address_1_field" class="form-row form-row-wide address-field validate-required">
                                            <label class="" for="billing_address_1">
                                                Address <abbr title="required" class="required">*</abbr>
                                            </label>
                                            <input type="text" value="" placeholder="Street address" asp-for="Address" class="input-text ">
                                            <span asp-validation-for="Address"></span>
                                        </p>







                                        <div class="clear"></div>



                                        <p id="billing_phone_field" class="form-row form-row-last validate-required validate-phone">
                                            <label class="" for="billing_phone">
                                                Phone <abbr title="required" class="required">*</abbr>
                                            </label>
                                            <input type="text" value="" placeholder="" asp-for="Phone" class="input-text ">
                                            <span asp-validation-for="Phone"></span>
                                        </p>
                                        <div class="clear"></div>




                                    </div>
                                </div>



                            </div>

                            <h3 id="order_review_heading">Sipariş Toplam</h3>

                            <div id="order_review" style="position: relative;">
                                @*OrderDetail*@
                                @await Component.InvokeAsync("OrderDetail")


                                <div id="payment">
                                    <ul class="payment_methods methods">
                                        <li class="payment_method_bacs">
                                            <input type="radio" data-order_button_text="" checked="checked" value="bacs" name="payment_method" class="input-radio" id="payment_method_bacs">
                                            <label for="payment_method_bacs">Direct Bank Transfer </label>
                                            <div class="payment_box payment_method_bacs">
                                                <p>Make your payment directly into our bank account. Please use your Order ID as the payment reference. Your order won’t be shipped until the funds have cleared in our account.</p>
                                            </div>
                                        </li>
                                        <li class="payment_method_cheque">
                                            <input type="radio" data-order_button_text="" value="cheque" name="payment_method" class="input-radio" id="payment_method_cheque">
                                            <label for="payment_method_cheque">Cheque Payment </label>
                                            <div style="display:none;" class="payment_box payment_method_cheque">
                                                <p>Please send your cheque to Store Name, Store Street, Store Town, Store State / County, Store Postcode.</p>
                                            </div>
                                        </li>
                                        <li class="payment_method_paypal">
                                            <input type="radio" data-order_button_text="Proceed to PayPal" value="paypal" name="payment_method" class="input-radio" id="payment_method_paypal">
                                            <label for="payment_method_paypal">
                                                PayPal <img alt="PayPal Acceptance Mark" src="https://www.paypalobjects.com/webstatic/mktg/Logo/AM_mc_vs_ms_ae_UK.png"><a title="What is PayPal?" onclick="javascript:window.open('https://www.paypal.com/gb/webapps/mpp/paypal-popup','WIPaypal','toolbar=no, location=no, directories=no, status=no, menubar=no, scrollbars=yes, resizable=yes, width=1060, height=700'); return false;" class="about_paypal" href="https://www.paypal.com/gb/webapps/mpp/paypal-popup">What is PayPal?</a>
                                            </label>
                                            <div style="display:none;" class="payment_box payment_method_paypal">
                                                <p>Pay via PayPal; you can pay with your credit card if you don’t have a PayPal account.</p>
                                            </div>
                                        </li>
                                    </ul>

                                    <div class="form-row place-order">

                                        <input type="submit" data-value="Place order" value="Place order" id="place_order" name="woocommerce_checkout_place_order" class="button alt">


                                    </div>

                                    <div class="clear"></div>

                                </div>
                            </div>
                        </form>

                    </div>
                </div>
            </div>
        </div>
    </div>
</div>