Eticaret.Presentation/Areas/Admin/Controllers/HomeController.cs
using Eticaret.Business.Helpers;
using Eticaret.Business.Services;
using Eticaret.Presentation.Areas.Admin.Models;
using Microsoft.AspNetCore.Mvc;
using System;

namespace Eticaret.Presentation.Areas.Admin.Controllers
{
    [Area("Admin")]
    public class HomeController : Controller
    {
        private readonly ICookieHelper _cookieHelper;
        private readonly IUserService _userService;
        private readonly IUserTokenService _userTokenService;

        public HomeController(ICookieHelper cookieHelper, IUserService userService, IUserTokenService userTokenService)
        {
            _cookieHelper = cookieHelper;
            _userService = userService;
            _userTokenService = userTokenService;
        }
        public IActionResult Index()
        {
            return View();
        }

        [HttpPost]
        public IActionResult Index(AdminLoginModel model)
        {
            if (ModelState.IsValid)
            {
                var login = _userService.AdminLogin(model.Email, model.Password);
                if (login == null)
                {
                    ModelState.AddModelError("LoginError", "Giriş Başarısız.");
                }
                else
                {
                    string guid = Guid.NewGuid().ToString();
                    _cookieHelper.Add(CookieTypes.admin, guid, DateTime.Now.AddDays(10), Response);
                    _userTokenService.Add(guid, login.Id);
                    return RedirectToAction("Index", "Dashboard");
                }
            }
            else
            {
                // bu model bir şekilde hatalı
            }
            return View();
        }
    }
}

Eticaret.Presentation/Controllers/HomeController.cs
using Eticaret.Business.Helpers;
using Eticaret.Business.Services;
using Eticaret.DataAccess.Concrete;
using Eticaret.Presentation.Models;
using Microsoft.AspNetCore.Mvc;
using System;
namespace Eticaret.Presentation.Controllers
{
    public class HomeController : Controller
    {
        private readonly ICookieHelper _cookieHelper;
        private readonly IUserService _userService;
        private readonly IUserTokenService _userTokenService;

        public HomeController(ICookieHelper cookieHelper, IUserService userService, IUserTokenService userTokenService)
        {
            _cookieHelper = cookieHelper;
            _userService = userService;
            _userTokenService = userTokenService;
        }

        public IActionResult Index()
        {
            //1
            return View();
        }
        // başında hiçbirşey yazmayan Action methodları GET işlemi yapar
        // sayfayı getirir.
        public IActionResult Login()
        {
            return View();
        }
        [HttpPost]
        public IActionResult Login(LoginModel model)
        {

            //Isvalid modelin geçerli olduğunu yani datalar doğru manasına gelir.
            if (ModelState.IsValid)
            {
                var login = _userService.Login(model.Email, model.Password);
                if (login == null)
                {
                    ModelState.AddModelError("LoginError", "Giriş Başarısız.");
                }
                else
                {
                    string guid = Guid.NewGuid().ToString();
                    _cookieHelper.Add(CookieTypes.user, guid, DateTime.Now.AddDays(10), Response);
                    _userTokenService.Add(guid, login.Id);
                    return RedirectToAction("Index", "Home");
                }
            }
            else
            {
                // bu model bir şekilde hatalı
            }


            return View();
        }
        public IActionResult Logout()
        {
        

            _cookieHelper.Delete(CookieTypes.user, Response);
            return RedirectToAction("Index");

        }

    }
}

Eticaret.Presentation/ViewComponents/HeaderAreaViewComponent.cs
using Eticaret.Business.Helpers;
using Eticaret.Business.Services;
using Microsoft.AspNetCore.Mvc;

namespace Eticaret.Presentation.ViewComponents
{
    public class HeaderAreaViewComponent : ViewComponent // eklenmeli
    {
        private readonly IUserService _userService;
        private readonly IUserTokenService _userTokenService;
        private readonly ICookieHelper _cookieHelper;
        public HeaderAreaViewComponent(IUserService userService, IUserTokenService userTokenService, ICookieHelper cookieHelper)
        {
            _userService = userService;
            _userTokenService = userTokenService;
            _cookieHelper = cookieHelper;
        }
        public IViewComponentResult Invoke() // Invoke standart ad
        {
            //2
            var cookie = _cookieHelper.Get(CookieTypes.user,Request);
            
            var tokenDetail = _userTokenService.Get(cookie);

            if (cookie == null || tokenDetail == null)
            {
                ViewData["email"] = null;
            }
            else
            {
                ViewData["email"] = _userService.GetById(tokenDetail.UserId).Email;
            }
           

            return View();
        }
    }
}

Eticaret.Presentation/ViewComponents/MainContentAreaViewComponent.cs
using Eticaret.Business.Services;
using Microsoft.AspNetCore.Mvc;

namespace Eticaret.Presentation.ViewComponents
{
    public class MainContentAreaViewComponent : ViewComponent
    {
        private readonly IProductService _productService;

        public MainContentAreaViewComponent(IProductService productService)
        {
            _productService = productService;
        }

        public IViewComponentResult Invoke()
        {
            var products = _productService.ProductWithImages();

            return View(products);
        }
    }
}

Eticaret.Presentation/ViewComponents/MainMenuAreaViewComponent.cs
using Eticaret.Business.Services;
using Microsoft.AspNetCore.Mvc;

namespace Eticaret.Presentation.ViewComponents
{
    public class MainMenuAreaViewComponent : ViewComponent
    {
        ICategoryService _categoryService;
        public MainMenuAreaViewComponent(ICategoryService categoryService)
        {
            _categoryService = categoryService;
        }
        public IViewComponentResult Invoke()
        {
            //4
            var result = _categoryService.List();

            return View(result);
        }
    }
}

Eticaret.Presentation/ViewComponents/SliderAreaViewComponent.cs
using Eticaret.Business.Services;
using Microsoft.AspNetCore.Mvc;

namespace Eticaret.Presentation.ViewComponents
{
    public class SliderAreaViewComponent : ViewComponent
    {
        ISliderService _sliderService;
        public SliderAreaViewComponent(ISliderService sliderService)
        {
            _sliderService = sliderService;
        }
        public IViewComponentResult Invoke()
        {
            //5
            var sliders = _sliderService.List();

            return View(sliders);
        }
    }
}

Eticaret.Presentation/Views/Home/Index.cshtml
@{
    Layout = null;
}
<!DOCTYPE html>
<!--
    ustora by freshdesignweb.com
    Twitter: https://twitter.com/freshdesignweb
    URL: https://www.freshdesignweb.com/ustora/
-->
<html lang="en">
<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>Ustora Demo</title>

    <!-- Google Fonts -->
    <link href='http://fonts.googleapis.com/css?family=Titillium+Web:400,200,300,700,600' rel='stylesheet' type='text/css'>
    <link href='http://fonts.googleapis.com/css?family=Roboto+Condensed:400,700,300' rel='stylesheet' type='text/css'>
    <link href='http://fonts.googleapis.com/css?family=Raleway:400,100' rel='stylesheet' type='text/css'>

    <!-- Bootstrap -->
    <link rel="stylesheet" href="/css/bootstrap.min.css">

    <!-- Font Awesome -->
    <link rel="stylesheet" href="/css/font-awesome.min.css">

    <!-- Custom CSS -->
    <link rel="stylesheet" href="/css/owl.carousel.css">
    <link rel="stylesheet" href="/style.css">
    <link rel="stylesheet" href="/css/responsive.css">

    <!-- HTML5 shim and Respond.js for IE8 support of HTML5 elements and media queries -->
    <!-- WARNING: Respond.js doesn't work if you view the page via file:// -->
    <!--[if lt IE 9]>
      <script src="/https://oss.maxcdn.com/html5shiv/3.7.2/html5shiv.min.js"></script>
      <script src="/https://oss.maxcdn.com/respond/1.4.2/respond.min.js"></script>
    <![endif]-->
</head>
<body>

    @await Component.InvokeAsync("HeaderArea")

    @await Component.InvokeAsync("SiteBrandingArea")

    @await Component.InvokeAsync("MainMenuArea")


    @await Component.InvokeAsync("SliderArea")

    <div class="promo-area">
        <div class="zigzag-bottom"></div>
        <div class="container">
            <div class="row">
                <div class="col-md-3 col-sm-6">
                    <div class="single-promo promo1">
                        <i class="fa fa-refresh"></i>
                        <p>30 Days return</p>
                    </div>
                </div>
                <div class="col-md-3 col-sm-6">
                    <div class="single-promo promo2">
                        <i class="fa fa-truck"></i>
                        <p>Free shipping</p>
                    </div>
                </div>
                <div class="col-md-3 col-sm-6">
                    <div class="single-promo promo3">
                        <i class="fa fa-lock"></i>
                        <p>Secure payments</p>
                    </div>
                </div>
                <div class="col-md-3 col-sm-6">
                    <div class="single-promo promo4">
                        <i class="fa fa-gift"></i>
                        <p>New products</p>
                    </div>
                </div>
            </div>
        </div>
    </div> <!-- End promo area -->
    @await Component.InvokeAsync("MainContentArea")

    <div class="brands-area">
        <div class="zigzag-bottom"></div>
        <div class="container">
            <div class="row">
                <div class="col-md-12">
                    <div class="brand-wrapper">
                        <div class="brand-list">
                            <img src="/img/brand1.png" alt="">
                            <img src="/img/brand2.png" alt="">
                            <img src="/img/brand3.png" alt="">
                            <img src="/img/brand4.png" alt="">
                            <img src="/img/brand5.png" alt="">
                            <img src="/img/brand6.png" alt="">
                            <img src="/img/brand1.png" alt="">
                            <img src="/img/brand2.png" alt="">
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div> <!-- End brands area -->
    @await Component.InvokeAsync("ProductWidgetArea")

    <div class="footer-top-area">
        <div class="zigzag-bottom"></div>
        <div class="container">
            <div class="row">
                <div class="col-md-3 col-sm-6">
                    <div class="footer-about-us">
                        <h2>u<span>Stora</span></h2>
                        <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Perferendis sunt id doloribus vero quam laborum quas alias dolores blanditiis iusto consequatur, modi aliquid eveniet eligendi iure eaque ipsam iste, pariatur omnis sint! Suscipit, debitis, quisquam. Laborum commodi veritatis magni at?</p>
                        <div class="footer-social">
                            <a href="#" target="_blank"><i class="fa fa-facebook"></i></a>
                            <a href="#" target="_blank"><i class="fa fa-twitter"></i></a>
                            <a href="#" target="_blank"><i class="fa fa-youtube"></i></a>
                            <a href="#" target="_blank"><i class="fa fa-linkedin"></i></a>
                        </div>
                    </div>
                </div>

                <div class="col-md-3 col-sm-6">
                    <div class="footer-menu">
                        <h2 class="footer-wid-title">User Navigation </h2>
                        <ul>
                            <li><a href="#">My account</a></li>
                            <li><a href="#">Order history</a></li>
                            <li><a href="#">Wishlist</a></li>
                            <li><a href="#">Vendor contact</a></li>
                            <li><a href="#">Front page</a></li>
                        </ul>
                    </div>
                </div>

                <div class="col-md-3 col-sm-6">
                    <div class="footer-menu">
                        <h2 class="footer-wid-title">Categories</h2>
                        <ul>
                            <li><a href="#">Mobile Phone</a></li>
                            <li><a href="#">Home accesseries</a></li>
                            <li><a href="#">LED TV</a></li>
                            <li><a href="#">Computer</a></li>
                            <li><a href="#">Gadets</a></li>
                        </ul>
                    </div>
                </div>

                <div class="col-md-3 col-sm-6">
                    <div class="footer-newsletter">
                        <h2 class="footer-wid-title">Newsletter</h2>
                        <p>Sign up to our newsletter and get exclusive deals you wont find anywhere else straight to your inbox!</p>
                        <div class="newsletter-form">
                            <form action="#">
                                <input type="email" placeholder="Type your email">
                                <input type="submit" value="Subscribe">
                            </form>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div> <!-- End footer top area -->

    <div class="footer-bottom-area">
        <div class="container">
            <div class="row">
                <div class="col-md-8">
                    <div class="copyright">
                        <p>&copy; 2015 uCommerce. All Rights Reserved. <a href="http://www.freshdesignweb.com" target="_blank">freshDesignweb.com</a></p>
                    </div>
                </div>

                <div class="col-md-4">
                    <div class="footer-card-icon">
                        <i class="fa fa-cc-discover"></i>
                        <i class="fa fa-cc-mastercard"></i>
                        <i class="fa fa-cc-paypal"></i>
                        <i class="fa fa-cc-visa"></i>
                    </div>
                </div>
            </div>
        </div>
    </div> <!-- End footer bottom area -->
    <!-- Latest jQuery form server -->
    <script src="https://code.jquery.com/jquery.min.js"></script>

    <!-- Bootstrap JS form CDN -->
    <script src="http://maxcdn.bootstrapcdn.com/bootstrap/3.2.0/js/bootstrap.min.js"></script>

    <!-- jQuery sticky menu -->
    <script src="/js/owl.carousel.min.js"></script>
    <script src="/js/jquery.sticky.js"></script>

    <!-- jQuery easing -->
    <script src="/js/jquery.easing.1.3.min.js"></script>

    <!-- Main Script -->
    <script src="/js/main.js"></script>

    <!-- Slider -->
    <script type="text/javascript" src="/js/bxslider.min.js"></script>
    <script type="text/javascript" src="/js/script.slider.js"></script>
      <script>
        function AddBasket(quantity,productId)
        {
            $.post("/basket",{quantityData:quantity,productIdData:productId},function(data,status){

                $("#basketDetail").html(data);
            });
        }
        $(document).ready(function(){

            $.post("/get-basket",{},function(data,status){
            
                $("#basketDetail").html(data);
            });
        });
    </script>
</body>
</html>

Eticaret.Presentation/Views/Home/Login.cshtml
@model LoginModel
@{
    Layout = "_LoginLayout";
}
<div class="container" style="background-color:#f4f4f4;padding:5px;border:solid 1px gray;width:550px;margin-left:auto;margin-right:auto;margin-bottom:25px;margin-top:25px">
  <h2>Login</h2>
  <form asp-controller="Home" asp-action="Login" method="post" target="_self">
    <div class="form-group">
      <label for="email">Email:</label>
      <input type="email" asp-for="Email" class="form-control" placeholder="Enter email" autocomplete="off">
     <span asp-validation-for="Email"></span>
    </div>
    <div class="form-group">
      <label for="pwd">Password:</label>
      <input type="password" asp-for="Password" class="form-control" placeholder="Enter password">
      <span asp-validation-for="Password"></span>
    </div>
    <div class="checkbox">
      <label><input type="checkbox"> Remember me</label>
    </div>
    <button type="submit" class="btn btn-default">Enter</button>
  </form>
</div>